name: LBA_Model
channels:
  - conda-forge
dependencies:
  - r-base=4.3
  - r-tidyverse
  - r-mvtnorm
  - r-pmwg
  - r-rtdists
  - r-knitr
  - r-rmarkdown
  - r-devtools
  - r-rcpp
  - r-coda
  - r-ggplot2
